// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUCa0T7QFXQNbzf1k9Uy1MgfOo0gNVvg',
    appId: '1:266991416176:web:a3f237a17745984f8355b5',
    messagingSenderId: '266991416176',
    projectId: 'plant-health-7a33b',
    authDomain: 'plant-health-7a33b.firebaseapp.com',
    storageBucket: 'plant-health-7a33b.firebasestorage.app',
    measurementId: 'G-S4RPJ7BE8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbqebAUhxwBEUQx2_iBg7bW9nSPjQEEI',
    appId: '1:266991416176:android:1bcc17e61685dc098355b5',
    messagingSenderId: '266991416176',
    projectId: 'plant-health-7a33b',
    storageBucket: 'plant-health-7a33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHa8CRceM8WvY_ylkdpdVrAhgr2Do8728',
    appId: '1:266991416176:ios:2900f6b13204b2c38355b5',
    messagingSenderId: '266991416176',
    projectId: 'plant-health-7a33b',
    storageBucket: 'plant-health-7a33b.firebasestorage.app',
    iosBundleId: 'com.example.plantHealth',
  );
}
